### ISSUE TITLE
[EPIC] Resume Feature

### ISSUE THREAD

**Issue by jtrenaud1s** [ARG-JR/ResumeBuilder#14]
## Description

End Users should be able to create a resume from pre-submitted pieces of information such as work experience, skills utilized, awards obtained, education obtained, and links to external sites.

Employers should be able to view published resumes belonging to users to find prospective employees.

System Administrators should be able to manage resumes, resume items, and user information in order to assist users with problems and questions they may face.

## User Stories

- [ ] As an End User, I want to manage Resume Items like Work Experience and Skills because I can globally add them to any of my resumes
- [ ] As an End User, I want to create resumes consisting of my submitted resume items because I can tailor different resumes to different job openings.
- [ ] As an End User, I want to manage all of my own resumes because this provides me the ability to create multiple resumes tailored to different job applications.
- [ ] As an End User, I want to be able to manage my personal profile because this information will be used in my resumes.

- [ ] As an Employer, I want to be able to see published resumes because it will help me find potential new-hires.
