### ISSUE TITLE
[STORY] User Resume Items

### ISSUE THREAD

**Issue by jtrenaud1s** [ARG-JR/ResumeBuilder#16]
Epic: #14 

## Description

ACTOR: End User

ACTION: Manage Resume Items

REASON: I can globally add them to any of my resumes.

## Tasks

- [ ] Create related Django Model(s)
  - [ ] Work Experience
  - [ ] Skill
  - [ ] Education
  - [ ] External Link
  - [ ] Awards
- [ ] Create related pages and views
  - [ ] Page to list all resume items belonging to the user in their own tables
  - [ ] Forms for creating and editing each type of resume item
    - Could done via popups instead of new pages (modals or off-canvas slide-in sidebars)
- [ ] CRUD Views for each model
  - [ ] Work Experience
    - [ ] Create
    - [ ] Read
    - [ ] Update
    - [ ] Delete
  - [ ] Skill
    - [ ] Create
    - [ ] Read
    - [ ] Update
    - [ ] Delete
  - [ ] Education
    - [ ] Create
    - [ ] Read
    - [ ] Update
    - [ ] Delete
  - [ ] External Link
    - [ ] Create
    - [ ] Read
    - [ ] Update
    - [ ] Delete
  - [ ] Awards
    - [ ] Create
    - [ ] Read
    - [ ] Update
    - [ ] Delete
- [ ] Seed table with sample data for each model
