### ISSUE TITLE
[STORY] User Resumes

### ISSUE THREAD

**Issue by jtrenaud1s** [ARG-JR/ResumeBuilder#17]
Epic: #14 
Depends on: #16 

## Description

ACTOR: End User

ACTION: Create resumes consisting of my submitted resume items

REASON: I can tailor different resumes to different job openings.

## Tasks

- [ ] Create Resume Django Model
- [ ] Seed resume table with test resume rows
- [ ] Create related Django views
- [ ] Create related Django templates
