### ISSUE TITLE
[STORY] User Profile Management

### ISSUE THREAD

**Issue by jtrenaud1s** [ARG-JR/ResumeBuilder#19]
Epic: #14 

## Description

ACTOR: End User

ACTION: Manage my personal profile

REASON: This information will be used in my resumes.

## Tasks

- [ ] Create related Django Model(s)
- [ ] Seed table with test data
- [ ] Create related Django views
- [ ] Create related Django templates
